// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: blockchain.proto

#include "blockchain.pb.h"
#include "blockchain.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* BlockchainService_method_names[] = {
  "/BlockchainService/AddTransaction",
};

std::unique_ptr< BlockchainService::Stub> BlockchainService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< BlockchainService::Stub> stub(new BlockchainService::Stub(channel, options));
  return stub;
}

BlockchainService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddTransaction_(BlockchainService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status BlockchainService::Stub::AddTransaction(::grpc::ClientContext* context, const ::TransactionRequest& request, ::TransactionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::TransactionRequest, ::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddTransaction_, context, request, response);
}

void BlockchainService::Stub::async::AddTransaction(::grpc::ClientContext* context, const ::TransactionRequest* request, ::TransactionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::TransactionRequest, ::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTransaction_, context, request, response, std::move(f));
}

void BlockchainService::Stub::async::AddTransaction(::grpc::ClientContext* context, const ::TransactionRequest* request, ::TransactionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddTransaction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TransactionResponse>* BlockchainService::Stub::PrepareAsyncAddTransactionRaw(::grpc::ClientContext* context, const ::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TransactionResponse, ::TransactionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddTransaction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TransactionResponse>* BlockchainService::Stub::AsyncAddTransactionRaw(::grpc::ClientContext* context, const ::TransactionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddTransactionRaw(context, request, cq);
  result->StartCall();
  return result;
}

BlockchainService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      BlockchainService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< BlockchainService::Service, ::TransactionRequest, ::TransactionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](BlockchainService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::TransactionRequest* req,
             ::TransactionResponse* resp) {
               return service->AddTransaction(ctx, req, resp);
             }, this)));
}

BlockchainService::Service::~Service() {
}

::grpc::Status BlockchainService::Service::AddTransaction(::grpc::ServerContext* context, const ::TransactionRequest* request, ::TransactionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


